### ISSUE TITLE
Faulty readme, Edgelab/examples folder has been removed

### ISSUE THREAD

**Issue by gbcarlos** [Seeed-Studio/edgelab-example-vision-ai#1]
Hi,

Step 5 in the [README](https://github.com/Seeed-Studio/edgelab-example-vision-ai) does not work anymore because the examples/vision_ai folder has been removed from the [Edgelab Repo](https://github.com/Seeed-Studio/EdgeLab). I can still see it in the backup branch though. Same issue also affects [this](https://github.com/Seeed-Studio/edgelab-example-vision-ai/blob/master/docs/en/Analog_meter_detection_existing_dataset.ipynb) file.

**Comment by LynnL4** [comment]
Hi, We have updated the docs, please refer [here](https://edgelab.readthedocs.io/en/latest/examples/edgelab-example-vision-ai/index.html).
