### ISSUE TITLE
Vision AI

### ISSUE THREAD

**Issue by namejinnameyuan** [Seeed-Studio/edgelab-example-vision-ai#2]
Compile the meter firmware according to the wiki process, and some errors occur, please tell me how to solve it, and the fomo firmware can be started normally.
![image](https://github.com/Seeed-Studio/edgelab-example-vision-ai/assets/35789561/d6511ada-ae53-470d-adf6-c90472aaffa7)

**Comment by LynnL4** [comment]
Hi，Have you flash the corresponding fomo model? What error occurs when compiling the meter firm

**Comment by namejinnameyuan** [comment]
Compile the firmware in the same way, only fomo can, and then the above problem occurs in the mete.
No problems when compiling the firmware.
![image](https://github.com/Seeed-Studio/edgelab-example-vision-ai/assets/35789561/3f4fa8e1-2140-487d-90d0-3fd221db8712)
![image](https://github.com/Seeed-Studio/edgelab-example-vision-ai/assets/35789561/9dc6a598-8d3d-4515-96b2-28717dd05b7d)
![image](https://github.com/Seeed-Studio/edgelab-example-vision-ai/assets/35789561/021bcb39-5e73-43ba-9f8b-4ad3b9828ce7)

**Comment by LynnL4** [comment]
Hi, I've updated the model and fixed some issues, you can pull it again, also this is the firmware I just compiled, after finishing the burn-in, you can preview the result through the [https://vision-ai-demo.seeed.cn/ page.](https://files.seeedstudio.com/grove_ai_vision/index.html)

[fomo_demo.zip](https://github.com/Seeed-Studio/edgelab-example-vision-ai/files/12309398/fomo_demo.zip)

**Comment by namejinnameyuan** [comment]
Is it right for the meter to appear like this?
![image](https://github.com/Seeed-Studio/edgelab-example-vision-ai/assets/35789561/c458476a-fca6-4a39-bd85-93bf0d161f4f)
Digital_meter compiles model.uf2 with pfld_meter_int8.tflite, or with another model_zone?

**Comment by LynnL4** [comment]
Hi, I have fixed the problem with the meter example, please re-pull the code, thanks!
![image](https://github.com/Seeed-Studio/edgelab-example-vision-ai/assets/51182126/47164d33-1284-41d4-8b26-fe5b37577fae)

**Comment by namejinnameyuan** [comment]
Excuse me, will the serial port output a value after the meter is detected?
Do I also use the pfld_meter_int8.tflite file for compiling the model.uf2 of the firmware digital_meter? Still need to recompile the int8 file

**Comment by LynnL4** [comment]
Yes, you need to upload both firmware and the model. 
After a successful upload, the example outputs a point at the end of a pointer. You can view the trace via the web

**Comment by namejinnameyuan** [comment]
Whether the serial port output information can see the data tracked by wbe.

**Comment by LynnL4** [comment]
It is not tracked in the current version and may be considered for inclusion in the future. You can open the serial port as well as the web app at the same time

**Comment by namejinnameyuan** [comment]
I also found a problem, after compiling make HW=grove_vision_ai APP=fomo && make flash, Total image size= 399 KB ( 0x63f10 ), and then compiling make HW=grove_vision_ai APP=meter && make flash, why Total image size= 399 KB ( 0x63f10 ) has not changed, because the first compilation size is 438KB, which is correct.

**Comment by LynnL4** [comment]
enen, when replacing a demo, you need a `make clean`, this should be caused by the existing makefile mechanism, we try to fix it, before that, please run `make clean` first.

**Comment by namejinnameyuan** [comment]
There is a mismatch when following the steps to use the Seeed-Studio/edgelab-model-zoo water meter model.
![image](https://github.com/Seeed-Studio/edgelab-example-vision-ai/assets/35789561/73db40c7-d802-4fee-ab23-00f1f5bef8ba)
![image](https://github.com/Seeed-Studio/edgelab-example-vision-ai/assets/35789561/dcde58c9-bdcb-4e80-ada9-4439fe3ca121)

**Comment by LynnL4** [comment]
I probably made changes to the ldscript that caused the current issue. Let me see how to fix it.

**Comment by namejinnameyuan** [comment]
Looking forward to your solution to the results, all models of yolov5 do not match

**Comment by namejinnameyuan** [comment]
(meter) Coordinates cannot be identified on the web page.
Has there been any progress on the above issues?

**Comment by LynnL4** [comment]
Hi,
You can get the latest relevant firmware as well as test models at this link 
https://github.com/Seeed-Studio/Seeed_Arduino_GroveAI/releases/tag/v2.0.0

- download [grove_ai_v02-00.uf2](https://github.com/Seeed-Studio/Seeed_Arduino_GroveAI/releases/download/v2.0.0/grove_ai_v02-00.uf2) then load it
- convert meter_seg7.tflite to .uf2 by uf2conv.py (-t <1-4> mean user define 1 - 4) then load it
- open url https://seeed-studio.github.io/edgelab-web-app/#/ 
- choose webserial & connect

We are in the process of reorganizing the interaction protocols between the device and the web-app, and will update the example when we are done with it.

**Comment by namejinnameyuan** [comment]
**convert meter_seg7.tflite to .uf2 by uf2conv.py (-t <1-4> mean user define 1 - 4) then load it**
Where is this available? I can't complete according to your steps. Has the problem mentioned before been solved?

**Comment by LynnL4** [comment]
Hi， Hi, I have converted meter_seg7 to uf2, please go to **[https://github.com/Seeed-Studio/Seeed_Arduino_GroveAI/releases/tag/v2.0.0](https://github.com/Seeed-Studio/Seeed_Arduino_GroveAI/releases/tag/v2.0)** to download it. For more models go to https://github.com/Seeed-Studio/edgelab-model-zoo
