### ISSUE TITLE
Does it support Grove Vision AI Module v2?

### ISSUE THREAD

**Issue by Aser-Abdelfatah** [Seeed-Studio/edgelab-example-vision-ai#4]
I'm wondering if it supports grove vision AI module v2. I have the v2 module, and despite being recognized with SenseCraft AI website, it never shows up in my disk explorer. I have a windows machine running windows 11.

**Comment by LynnL4** [comment]
HiThe project for the grove vision AI module v2 is in this repository https://github.com/Seeed-Studio/sscma-example-we2

**Comment by Lesords** [comment]
Hello,

I\'m going to close this issue, feel free to re-open it if you have any other questions.

[Autocommentary]
